version: "3.9"

services:
  web:
    build: .
    command: bash -c "python manage.py migrate & python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7


  celery:
    build: .
    command: celery -A config worker --loglevel=info

    depends_on:
      - redis
      - db


networks:
  default:

volumes:
  postgres_data:
  static_volume:
